name: Dependency Review

on:
  pull_request: ~

permissions: {}

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      deps: ${{ steps.filter.outputs.deps }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            deps:
              - 'pyproject.toml'
              - 'uv.lock'

  dependency-review:
    needs: filter
    if: needs.filter.outputs.deps == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Acquire sources
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
