name: Typecheck

on:
  push:
    branches: [ main ]
  pull_request: ~

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  PYTHON: "3.14"

permissions: {}

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON }}

      - name: Install project
        run: uv sync --group test --extra duckdb

      - name: Run type checks
        run: uv run poe type
